### ISSUE TITLE
Final Capstone Project

### ISSUE THREAD

**Issue by usmansbk** [usmansbk/rooms-backend#34]
Project: [Kanban Board](https://github.com/usmansbk/rooms-backend/projects/1)

This group is comprised of the following 4 members:

1. Usman - @usmansbk 
2. Denis - @denisdiaconu
3. Olawale - @olawale-o
4. Simon - @SimonGrchevski

![Screenshot 2021-11-29 at 17-38-52 Final Capstone Project · usmansbk rooms-backend](https://user-images.githubusercontent.com/10219539/143907673-0d2f2af8-08e0-4952-8c50-72d43f99639f.png)

**Comment by MuriloRoque** [comment]
Hi @usmansbk, @olawale-o, @denisdiaconu, @SimonGrchevski, 

In my opinion, your project is approved!  There is nothing else to say other than... it's time to start it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
